/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"

#import "owbop.h"
#import "owbsys.h"

@protocol owbdata_provider <NSObject>
- (NSMutableArray *) GetOps: (NSString *) mid opid: (int32_t) opid;  // throws TException
- (NSMutableArray *) Restore: (NSString *) mid;  // throws TException
@end

@interface owbdata_providerClient : NSObject <owbdata_provider> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface owbdata_providerProcessor : NSObject <TProcessor> {
  id <owbdata_provider> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithdata_provider: (id <owbdata_provider>) service;
- (id<owbdata_provider>) service;
@end

@protocol owbdata_updater <NSObject>
- (int32_t) SendOp: (owbOwbOp *) op;  // throws TException
@end

@interface owbdata_updaterClient : NSObject <owbdata_updater> {
id <TProtocol> inProtocol;
id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface owbdata_updaterProcessor : NSObject <TProcessor> {
id <owbdata_updater> mService;
NSDictionary * mMethodMap;
}
- (id) initWithdata_updater: (id <owbdata_updater>) service;
- (id<owbdata_updater>) service;
@end

@protocol owbmaster <NSObject>
- (BOOL) TransferAuth: (NSString *) hname mid: (NSString *) mid;  // throws TException
- (NSMutableArray *) GetUserList: (NSString *) mid;  // throws TException
- (owbOwbHbRPack *) HeartBeat: (owbOwbHbSPack *) pack;  // throws TException
@end

@interface owbmasterClient : NSObject <owbmaster> {
id <TProtocol> inProtocol;
id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface owbmasterProcessor : NSObject <TProcessor> {
id <owbmaster> mService;
NSDictionary * mMethodMap;
}
- (id) initWithmaster: (id <owbmaster>) service;
- (id<owbmaster>) service;
@end

@protocol owbmanager <NSObject>
- (BOOL) Login: (owbOwbUser *) user;  // throws TException
- (owbOwbServerInfo *) JoinMeeting: (NSString *) uname mid: (NSString *) mid;  // throws owbOwbMissingMeeting *, owbOwbDeadMeeting *, TException
- (NSString *) CreateMeeting: (NSString *) uname;  // throws TException
@end

@interface owbmanagerClient : NSObject <owbmanager> {
id <TProtocol> inProtocol;
id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface owbmanagerProcessor : NSObject <TProcessor> {
id <owbmanager> mService;
NSDictionary * mMethodMap;
}
- (id) initWithmanager: (id <owbmanager>) service;
- (id<owbmanager>) service;
@end

@interface owbowbserviceConstants : NSObject {
}
@end
