/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"


enum owbOwbUserIdentity {
  OwbUserIdentity_HOST = 0,
  OwbUserIdentity_CANDIDATE = 1,
  OwbUserIdentity_PARTICIPANTS = 2
};

@interface owbOwbMissingMeeting : NSException <NSCoding> {
  NSString * __descripe;

  BOOL __descripe_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=descripe, setter=setDescripe:) NSString * descripe;
#endif

- (id) init;
- (id) initWithDescripe: (NSString *) descripe;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) descripe;
- (void) setDescripe: (NSString *) descripe;
#endif
- (BOOL) descripeIsSet;

@end

@interface owbOwbDeadMeeting : NSException <NSCoding> {
  NSString * __descripe;

  BOOL __descripe_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=descripe, setter=setDescripe:) NSString * descripe;
#endif

- (id) init;
- (id) initWithDescripe: (NSString *) descripe;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) descripe;
- (void) setDescripe: (NSString *) descripe;
#endif
- (BOOL) descripeIsSet;

@end

@interface owbOwbServerInfo : NSObject <NSCoding> {
  NSString * __ip;
  int32_t __master_port;
  int32_t __updator_port;
  int32_t __provider_port;

  BOOL __ip_isset;
  BOOL __master_port_isset;
  BOOL __updator_port_isset;
  BOOL __provider_port_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=ip, setter=setIp:) NSString * ip;
@property (nonatomic, getter=master_port, setter=setMaster_port:) int32_t master_port;
@property (nonatomic, getter=updator_port, setter=setUpdator_port:) int32_t updator_port;
@property (nonatomic, getter=provider_port, setter=setProvider_port:) int32_t provider_port;
#endif

- (id) init;
- (id) initWithIp: (NSString *) ip master_port: (int32_t) master_port updator_port: (int32_t) updator_port provider_port: (int32_t) provider_port;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) ip;
- (void) setIp: (NSString *) ip;
#endif
- (BOOL) ipIsSet;

#if !__has_feature(objc_arc)
- (int32_t) master_port;
- (void) setMaster_port: (int32_t) master_port;
#endif
- (BOOL) master_portIsSet;

#if !__has_feature(objc_arc)
- (int32_t) updator_port;
- (void) setUpdator_port: (int32_t) updator_port;
#endif
- (BOOL) updator_portIsSet;

#if !__has_feature(objc_arc)
- (int32_t) provider_port;
- (void) setProvider_port: (int32_t) provider_port;
#endif
- (BOOL) provider_portIsSet;

@end

@interface owbOwbUser : NSObject <NSCoding> {
  NSString * __uname;
  NSString * __passwd;
  int __identity;

  BOOL __uname_isset;
  BOOL __passwd_isset;
  BOOL __identity_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=uname, setter=setUname:) NSString * uname;
@property (nonatomic, retain, getter=passwd, setter=setPasswd:) NSString * passwd;
@property (nonatomic, getter=identity, setter=setIdentity:) int identity;
#endif

- (id) init;
- (id) initWithUname: (NSString *) uname passwd: (NSString *) passwd identity: (int) identity;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) uname;
- (void) setUname: (NSString *) uname;
#endif
- (BOOL) unameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) passwd;
- (void) setPasswd: (NSString *) passwd;
#endif
- (BOOL) passwdIsSet;

#if !__has_feature(objc_arc)
- (int) identity;
- (void) setIdentity: (int) identity;
#endif
- (BOOL) identityIsSet;

@end

@interface owbOwbHbSPack : NSObject <NSCoding> {
  NSString * __uname;
  NSString * __mid;

  BOOL __uname_isset;
  BOOL __mid_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=uname, setter=setUname:) NSString * uname;
@property (nonatomic, retain, getter=mid, setter=setMid:) NSString * mid;
#endif

- (id) init;
- (id) initWithUname: (NSString *) uname mid: (NSString *) mid;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) uname;
- (void) setUname: (NSString *) uname;
#endif
- (BOOL) unameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) mid;
- (void) setMid: (NSString *) mid;
#endif
- (BOOL) midIsSet;

@end

@interface owbOwbHbRPack : NSObject <NSCoding> {
  int __identity;

  BOOL __identity_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=identity, setter=setIdentity:) int identity;
#endif

- (id) init;
- (id) initWithIdentity: (int) identity;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int) identity;
- (void) setIdentity: (int) identity;
#endif
- (BOOL) identityIsSet;

@end

@interface owbowbsysConstants : NSObject {
}
@end
